var searchData=
[
  ['elite_5fpopulation_5freplace_0',['elite_population_replace',['../structlocusta_1_1ga__solver__cuda.html#a5f46d0fbcb1784764ee1ab6fcea3d13c',1,'locusta::ga_solver_cuda::elite_population_replace()'],['../structlocusta_1_1ga__solver__cpu.html#a2bbc618f4956d3bf569a0bab1e4aa898',1,'locusta::ga_solver_cpu::elite_population_replace()']]],
  ['elite_5fpopulation_5freplace_5fdispatch_1',['elite_population_replace_dispatch',['../namespacelocusta.html#aaa013dee0f1b3fcde721b80f334137cf',1,'locusta']]],
  ['ellips_2',['ellips',['../namespacelocusta.html#a48c7136b9cf87bc45fe3290857ae1d1d',1,'locusta']]],
  ['evaluable_5ffunction_2ehpp_3',['evaluable_function.hpp',['../evaluable__function_8hpp.html',1,'']]],
  ['evaluable_5ffunction_5fcuda_2ehpp_4',['evaluable_function_cuda.hpp',['../evaluable__function__cuda_8hpp.html',1,'']]],
  ['evaluate_5',['evaluate',['../structlocusta_1_1evaluator__cuda.html#acbc6b6c20071bb0a21200c7c85bf8ac6',1,'locusta::evaluator_cuda::evaluate()'],['../structlocusta_1_1evaluator__cpu.html#a1c1f3d8f27a6206a8ef215324d2024af',1,'locusta::evaluator_cpu::evaluate()'],['../structlocusta_1_1evaluator.html#accd7b2fd2957cf31ee4957fa2f63d6d1',1,'locusta::evaluator::evaluate()']]],
  ['evaluate_5fgenomes_6',['evaluate_genomes',['../structlocusta_1_1evolutionary__solver__cuda.html#a0ab3176e617af00f4e07f40e1dedae86',1,'locusta::evolutionary_solver_cuda::evaluate_genomes()'],['../structlocusta_1_1evolutionary__solver.html#a9b75a9dc2938714da717f7d0d4e2d01f',1,'locusta::evolutionary_solver::evaluate_genomes()']]],
  ['evaluating_20evolutionary_20algorithms_20on_20parallel_20architectures_7',['Locusta - A Framework for Analyzing and Evaluating Evolutionary Algorithms on Parallel Architectures',['../index.html',1,'']]],
  ['evaluation_5ffunctor_5fcpu_5fptr_8',['evaluation_functor_cpu_ptr',['../class_c_p_u_locusta_test.html#a3225fd7a7b5ec9826d50e5bf1e7f9e8f',1,'CPULocustaTest']]],
  ['evaluation_5ffunctor_5fcuda_5fptr_9',['evaluation_functor_cuda_ptr',['../class_g_p_u_locusta_test.html#ad98f40e57c7d480671870bc350ce27dc',1,'GPULocustaTest']]],
  ['evaluationcudafunctor_10',['EvaluationCudaFunctor',['../structlocusta_1_1_evaluation_cuda_functor.html',1,'locusta']]],
  ['evaluationcudafunctor_3c_20float_20_3e_11',['EvaluationCudaFunctor&lt; float &gt;',['../structlocusta_1_1_evaluation_cuda_functor.html',1,'locusta']]],
  ['evaluationfunctor_12',['EvaluationFunctor',['../structlocusta_1_1_evaluation_functor.html',1,'locusta']]],
  ['evaluationfunctor_3c_20float_20_3e_13',['EvaluationFunctor&lt; float &gt;',['../structlocusta_1_1_evaluation_functor.html',1,'locusta']]],
  ['evaluator_14',['evaluator',['../structlocusta_1_1evaluator.html',1,'locusta::evaluator&lt; TFloat &gt;'],['../structlocusta_1_1evaluator.html#abce29714dfb15dff9e76cfd2b7897cf2',1,'locusta::evaluator::evaluator()']]],
  ['evaluator_2ehpp_15',['evaluator.hpp',['../evaluator_8hpp.html',1,'']]],
  ['evaluator_3c_20float_20_3e_16',['evaluator&lt; float &gt;',['../structlocusta_1_1evaluator.html',1,'locusta']]],
  ['evaluator_5fcpu_17',['evaluator_cpu',['../structlocusta_1_1evaluator__cpu.html#a2b309694d16faab1850fabf1bc1ac8ef',1,'locusta::evaluator_cpu::evaluator_cpu()'],['../structlocusta_1_1evaluator__cpu.html',1,'locusta::evaluator_cpu&lt; TFloat &gt;']]],
  ['evaluator_5fcpu_2ehpp_18',['evaluator_cpu.hpp',['../evaluator__cpu_8hpp.html',1,'']]],
  ['evaluator_5fcpu_3c_20float_20_3e_19',['evaluator_cpu&lt; float &gt;',['../structlocusta_1_1evaluator__cpu.html',1,'locusta']]],
  ['evaluator_5fcpu_5fimpl_2ehpp_20',['evaluator_cpu_impl.hpp',['../evaluator__cpu__impl_8hpp.html',1,'']]],
  ['evaluator_5fcpu_5fptr_21',['evaluator_cpu_ptr',['../class_c_p_u_locusta_test.html#af48840564ae3c0a5590b9ddfde652b10',1,'CPULocustaTest']]],
  ['evaluator_5fcuda_22',['evaluator_cuda',['../structlocusta_1_1evaluator__cuda.html#a83c5a75900980f688bb85d09250c1ae1',1,'locusta::evaluator_cuda::evaluator_cuda()'],['../structlocusta_1_1evaluator__cuda.html',1,'locusta::evaluator_cuda&lt; TFloat &gt;']]],
  ['evaluator_5fcuda_2ehpp_23',['evaluator_cuda.hpp',['../evaluator__cuda_8hpp.html',1,'']]],
  ['evaluator_5fcuda_3c_20float_20_3e_24',['evaluator_cuda&lt; float &gt;',['../structlocusta_1_1evaluator__cuda.html',1,'locusta']]],
  ['evaluator_5fcuda_5fimpl_2ehpp_25',['evaluator_cuda_impl.hpp',['../evaluator__cuda__impl_8hpp.html',1,'']]],
  ['evaluator_5fcuda_5fptr_26',['evaluator_cuda_ptr',['../class_g_p_u_locusta_test.html#ada3927aeb01a9baf6670e81f38ffea9f',1,'GPULocustaTest']]],
  ['evolutionary_20algorithms_20on_20parallel_20architectures_27',['Locusta - A Framework for Analyzing and Evaluating Evolutionary Algorithms on Parallel Architectures',['../index.html',1,'']]],
  ['evolutionary_5fsolver_28',['evolutionary_solver',['../structlocusta_1_1evolutionary__solver.html',1,'locusta::evolutionary_solver&lt; TFloat &gt;'],['../structlocusta_1_1evolutionary__solver.html#ab67154f48814852776a255afe2a28ba7',1,'locusta::evolutionary_solver::evolutionary_solver()']]],
  ['evolutionary_5fsolver_2ehpp_29',['evolutionary_solver.hpp',['../evolutionary__solver_8hpp.html',1,'']]],
  ['evolutionary_5fsolver_3c_20float_20_3e_30',['evolutionary_solver&lt; float &gt;',['../structlocusta_1_1evolutionary__solver.html',1,'locusta']]],
  ['evolutionary_5fsolver_5fcpu_31',['evolutionary_solver_cpu',['../structlocusta_1_1evolutionary__solver__cpu.html',1,'locusta::evolutionary_solver_cpu&lt; TFloat &gt;'],['../structlocusta_1_1evolutionary__solver__cpu.html#a5bba901ff4d6a1c1d0613a628d319ac5',1,'locusta::evolutionary_solver_cpu::evolutionary_solver_cpu()']]],
  ['evolutionary_5fsolver_5fcpu_2ehpp_32',['evolutionary_solver_cpu.hpp',['../evolutionary__solver__cpu_8hpp.html',1,'']]],
  ['evolutionary_5fsolver_5fcpu_3c_20float_20_3e_33',['evolutionary_solver_cpu&lt; float &gt;',['../structlocusta_1_1evolutionary__solver__cpu.html',1,'locusta']]],
  ['evolutionary_5fsolver_5fcpu_5fimpl_2ehpp_34',['evolutionary_solver_cpu_impl.hpp',['../evolutionary__solver__cpu__impl_8hpp.html',1,'']]],
  ['evolutionary_5fsolver_5fcuda_35',['evolutionary_solver_cuda',['../structlocusta_1_1evolutionary__solver__cuda.html#a1eebeeab62b0115b136ce6652af2a688',1,'locusta::evolutionary_solver_cuda::evolutionary_solver_cuda()'],['../structlocusta_1_1evolutionary__solver__cuda.html',1,'locusta::evolutionary_solver_cuda&lt; TFloat &gt;']]],
  ['evolutionary_5fsolver_5fcuda_2ecu_36',['evolutionary_solver_cuda.cu',['../evolutionary__solver__cuda_8cu.html',1,'']]],
  ['evolutionary_5fsolver_5fcuda_2ehpp_37',['evolutionary_solver_cuda.hpp',['../evolutionary__solver__cuda_8hpp.html',1,'']]],
  ['evolutionary_5fsolver_5fcuda_3c_20float_20_3e_38',['evolutionary_solver_cuda&lt; float &gt;',['../structlocusta_1_1evolutionary__solver__cuda.html',1,'locusta']]],
  ['evolutionary_5fsolver_5fcuda_5fimpl_2ehpp_39',['evolutionary_solver_cuda_impl.hpp',['../evolutionary__solver__cuda__impl_8hpp.html',1,'']]],
  ['evolutionary_5fsolver_5fimpl_2ehpp_40',['evolutionary_solver_impl.hpp',['../evolutionary__solver__impl_8hpp.html',1,'']]],
  ['example_20application_41',['Building the Example Application',['../index.html#building_app',1,'']]],
  ['examples_42',['Examples',['../index.html#example_sec',1,'']]]
];
